-- Microline v1 şeması. Konvansiyonlar:
--   * Çevrilebilir alanlar _tr/_en çiftidir; _tr NOT NULL (Türkçe zorunlu, İngilizce opsiyonel).
--   * PK'ler BIGINT GENERATED BY DEFAULT AS IDENTITY (JPA GenerationType.IDENTITY ile uyumlu).
--   * created_at/updated_at JPA auditing tarafından set edilir; DEFAULT now() yalnızca elle
--     yapılan seed/INSERT'ler için emniyettir.

CREATE TABLE collections (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(30)  NOT NULL,
    slug_tr         VARCHAR(150) NOT NULL,
    slug_en         VARCHAR(150),
    name_tr         VARCHAR(200) NOT NULL,
    name_en         VARCHAR(200),
    description_tr  TEXT         NOT NULL,
    description_en  TEXT,
    hero_image_url  VARCHAR(500),
    sort_order      INT          NOT NULL DEFAULT 0,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_collections_code    UNIQUE (code),
    CONSTRAINT uq_collections_slug_tr UNIQUE (slug_tr),
    CONSTRAINT uq_collections_slug_en UNIQUE (slug_en)
);

CREATE TABLE products (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku                  VARCHAR(40)   NOT NULL,
    slug_tr              VARCHAR(150)  NOT NULL,
    slug_en              VARCHAR(150),
    name_tr              VARCHAR(200)  NOT NULL,
    name_en              VARCHAR(200),
    tagline_tr           VARCHAR(300)  NOT NULL,
    tagline_en           VARCHAR(300),
    description_tr       TEXT          NOT NULL,
    description_en       TEXT,
    safety_notes_tr      TEXT          NOT NULL,
    safety_notes_en      TEXT,
    specs_json           JSONB,
    price_amount         NUMERIC(10,2) NOT NULL,
    currency             VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    compare_at_price     NUMERIC(10,2),
    collection_id        BIGINT        NOT NULL REFERENCES collections (id),
    hero_image_url       VARCHAR(500),
    featured             BOOLEAN       NOT NULL DEFAULT FALSE,
    active               BOOLEAN       NOT NULL DEFAULT TRUE,
    sort_order           INT           NOT NULL DEFAULT 0,
    meta_description_tr  VARCHAR(300)  NOT NULL,
    meta_description_en  VARCHAR(300),
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_sku     UNIQUE (sku),
    CONSTRAINT uq_products_slug_tr UNIQUE (slug_tr),
    CONSTRAINT uq_products_slug_en UNIQUE (slug_en)
);

CREATE INDEX idx_products_collection_id ON products (collection_id);

CREATE TABLE product_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    url         VARCHAR(500) NOT NULL,
    alt_tr      VARCHAR(300) NOT NULL,
    alt_en      VARCHAR(300),
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_images_product_id ON product_images (product_id);

-- Varyantlar v2'de sipariş satırlarından referans alacak: ON DELETE CASCADE yok,
-- pasifleştirme (active=false) tercih edilir.
CREATE TABLE product_variants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT        NOT NULL REFERENCES products (id),
    sku          VARCHAR(40)   NOT NULL,
    name_tr      VARCHAR(200)  NOT NULL,
    name_en      VARCHAR(200),
    price_delta  NUMERIC(10,2) NOT NULL DEFAULT 0,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    sort_order   INT           NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_product_variants_sku UNIQUE (sku)
);

CREATE INDEX idx_product_variants_product_id ON product_variants (product_id);

-- Yorumlar tek dilli orijinaldir (locale kolonuyla filtrelenir); author_title_tr/en
-- bilingual kuralın istisnasıdır (ikisi de opsiyonel kısa unvan).
CREATE TABLE reviews (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT REFERENCES products (id),
    author_name      VARCHAR(150) NOT NULL,
    author_title_tr  VARCHAR(200),
    author_title_en  VARCHAR(200),
    rating           SMALLINT     NOT NULL,
    body             TEXT         NOT NULL,
    locale           VARCHAR(2)   NOT NULL,
    featured         BOOLEAN      NOT NULL DEFAULT FALSE,
    approved         BOOLEAN      NOT NULL DEFAULT FALSE,
    source           VARCHAR(150),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_reviews_product_id ON reviews (product_id);

CREATE TABLE tutorial_posts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug_tr          VARCHAR(150) NOT NULL,
    slug_en          VARCHAR(150),
    title_tr         VARCHAR(300) NOT NULL,
    title_en         VARCHAR(300),
    excerpt_tr       TEXT         NOT NULL,
    excerpt_en       TEXT,
    body_tr          TEXT         NOT NULL,
    body_en          TEXT,
    cover_image_url  VARCHAR(500),
    video_url        VARCHAR(500),
    difficulty       VARCHAR(20)  NOT NULL,
    published        BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tutorial_posts_slug_tr UNIQUE (slug_tr),
    CONSTRAINT uq_tutorial_posts_slug_en UNIQUE (slug_en)
);

CREATE TABLE legal_pages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      VARCHAR(50)  NOT NULL,
    slug_tr   VARCHAR(150) NOT NULL,
    slug_en   VARCHAR(150),
    title_tr  VARCHAR(300) NOT NULL,
    title_en  VARCHAR(300),
    body_tr   TEXT         NOT NULL,
    body_en   TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_legal_pages_code    UNIQUE (code),
    CONSTRAINT uq_legal_pages_slug_tr UNIQUE (slug_tr),
    CONSTRAINT uq_legal_pages_slug_en UNIQUE (slug_en)
);

CREATE TABLE order_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    phone         VARCHAR(30)  NOT NULL,
    product_id    BIGINT       NOT NULL REFERENCES products (id),
    variant_id    BIGINT REFERENCES product_variants (id),
    quantity      INT          NOT NULL DEFAULT 1,
    message       TEXT,
    status        VARCHAR(20)  NOT NULL DEFAULT 'NEW',
    kvkk_consent  BOOLEAN      NOT NULL,
    locale        VARCHAR(2)   NOT NULL,
    source_ip     VARCHAR(45),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_order_requests_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_order_requests_product_id ON order_requests (product_id);

CREATE TABLE contact_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    subject       VARCHAR(300) NOT NULL,
    message       TEXT         NOT NULL,
    kvkk_consent  BOOLEAN      NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'NEW',
    locale        VARCHAR(2)   NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Abone satırı silinmez (KVKK rıza kaydı); çıkış unsubscribed_at ile işaretlenir.
CREATE TABLE newsletter_subscribers (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    locale             VARCHAR(2)   NOT NULL,
    kvkk_consent_at    TIMESTAMPTZ  NOT NULL,
    unsubscribe_token  UUID         NOT NULL,
    unsubscribed_at    TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_newsletter_subscribers_email UNIQUE (email),
    CONSTRAINT uq_newsletter_subscribers_token UNIQUE (unsubscribe_token)
);
