-- Sepet: bir sipariş talebi artık birden çok satır içerir. Ödeme olmadığı
-- için fiyatı hiçbir şey kilitlemiyor; talep ANINDAKİ birim fiyat satıra
-- snapshot'lanır (satış aramasında müşterinin ne gördüğü kayıtlı olsun).
CREATE TABLE order_request_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_request_id BIGINT        NOT NULL REFERENCES order_requests (id) ON DELETE CASCADE,
    product_id       BIGINT        NOT NULL REFERENCES products (id),
    variant_id       BIGINT        REFERENCES product_variants (id),
    quantity         INT           NOT NULL CHECK (quantity BETWEEN 1 AND 999),
    unit_price       NUMERIC(10,2) NOT NULL,
    currency         VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_request_items_request ON order_request_items (order_request_id);
CREATE INDEX idx_order_request_items_product ON order_request_items (product_id);

-- NOT: (order_request_id, product_id, variant_id) UNIQUE kısıtı bilinçli yok —
-- PG14'te NULLS NOT DISTINCT olmadığından NULL varyantlar kısıtı atlatır;
-- satır birleştirme CartService'te uygulanır. PG15+ geçişinde eklenebilir.

-- Mevcut tek-ürün satırlarını taşı (unit_price geriye dönük bilinemez;
-- bugünkü fiyat yazılır — eldeki veri yalnızca dev test verisidir).
INSERT INTO order_request_items (order_request_id, product_id, variant_id, quantity, unit_price, currency)
SELECT o.id, o.product_id, o.variant_id, o.quantity,
       p.price_amount + COALESCE(v.price_delta, 0), p.currency
FROM order_requests o
JOIN products p ON p.id = o.product_id
LEFT JOIN product_variants v ON v.id = o.variant_id;

-- Tek-ürün kolonları kalkar (temiz kırılım; prod verisi yok, taşıma yukarıda).
ALTER TABLE order_requests
    DROP COLUMN product_id,
    DROP COLUMN variant_id,
    DROP COLUMN quantity;
