-- Yönetim paneli kullanıcıları. Seed satırı BİLEREK yok: git'e şifre hash'i
-- girmemek için ilk admin AdminUserInitializer (ApplicationRunner) tarafından
-- tablo boşken oluşturulur (microline.admin.initial-username/-password).
-- password_hash VARCHAR(100): BCrypt çıktısı 60 karakter, pay güvenli.

CREATE TABLE admin_users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    display_name   VARCHAR(150) NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_admin_users_username UNIQUE (username)
);
